
services:
  postgres:
    container_name: chess_db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
      
  testdb:
    container_name: test_db
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data_test:/var/lib/postgresql/data
    env_file:
      - .env.test
volumes:
  postgres-data:
  postgres-data_test: